[2025-03-20T10:34:41.170+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-20T10:34:26.149403+00:00 [queued]>
[2025-03-20T10:34:41.181+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-20T10:34:26.149403+00:00 [queued]>
[2025-03-20T10:34:41.183+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-20T10:34:41.199+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud> on 2025-03-20 10:34:26.149403+00:00
[2025-03-20T10:34:41.205+0000] {standard_task_runner.py:57} INFO - Started process 491 to run task
[2025-03-20T10:34:41.209+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud', 'manual__2025-03-20T10:34:26.149403+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp81l01oiu']
[2025-03-20T10:34:41.212+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask detect_fraud
[2025-03-20T10:34:41.279+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-20T10:34:26.149403+00:00 [running]> on host bb4292cadea3
[2025-03-20T10:34:41.451+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T10:34:26.149403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T10:34:26.149403+00:00'
[2025-03-20T10:34:41.453+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-20T10:34:41.454+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e"\n    CREATE TABLE IF NOT EXISTS fraud_detections (\n        transaction_id STRING,\n        date_time STRING,\n        amount DOUBLE,\n        customer_id STRING,\n        location STRING,\n        fraud_reason STRING\n    )\n    STORED AS PARQUET\n    LOCATION \'/data/fraud_detections\';\n    INSERT INTO TABLE fraud_detections\n    SELECT\n        t.transaction_id,\n        t.date_time,\n        t.amount,\n        t.customer_id,\n        t.location,\n        \'High Amount\' AS fraud_reason\n    FROM transactions t\n    WHERE t.batch_id = \'batch_0\'\n    AND t.amount > 1000;"\n    ']
[2025-03-20T10:34:41.469+0000] {subprocess.py:86} INFO - Output:
[2025-03-20T10:34:42.671+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-20T10:34:42.672+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-20T10:34:42.673+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-20T10:34:42.674+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-20T10:34:42.842+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-20T10:34:44.058+0000] {subprocess.py:93} INFO - Connecting to jdbc:hive2://localhost:10000
[2025-03-20T10:34:44.274+0000] {subprocess.py:93} INFO - Connected to: Apache Hive (version 3.1.3)
[2025-03-20T10:34:44.275+0000] {subprocess.py:93} INFO - Driver: Hive JDBC (version 3.1.3)
[2025-03-20T10:34:44.276+0000] {subprocess.py:93} INFO - Transaction isolation: TRANSACTION_REPEATABLE_READ
[2025-03-20T10:34:44.367+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250320103444_c58a7a7e-58ce-477e-8bf4-a2391eb5e145): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-20T10:34:44.369+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-20T10:34:44.369+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-20T10:34:44.370+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-20T10:34:44.371+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-20T10:34:44.372+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-20T10:34:44.372+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-20T10:34:44.373+0000] {subprocess.py:93} INFO -     )
[2025-03-20T10:34:44.373+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-20T10:34:44.374+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-20T10:34:44.375+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:44.376+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-20T10:34:44.376+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
[2025-03-20T10:34:44.377+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250320103444_c58a7a7e-58ce-477e-8bf4-a2391eb5e145); Time taken: 0.019 seconds
[2025-03-20T10:34:44.378+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:44.378+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250320103444_c58a7a7e-58ce-477e-8bf4-a2391eb5e145): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-20T10:34:44.379+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-20T10:34:44.380+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-20T10:34:44.381+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-20T10:34:44.381+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-20T10:34:44.382+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-20T10:34:44.382+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-20T10:34:44.383+0000] {subprocess.py:93} INFO -     )
[2025-03-20T10:34:44.383+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-20T10:34:44.384+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-20T10:34:44.384+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250320103444_c58a7a7e-58ce-477e-8bf4-a2391eb5e145); Time taken: 0.002 seconds
[2025-03-20T10:34:44.384+0000] {subprocess.py:93} INFO - INFO  : OK
[2025-03-20T10:34:44.385+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:44.385+0000] {subprocess.py:93} INFO - No rows affected (0.075 seconds)
[2025-03-20T10:34:45.705+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250320103444_4cf7616b-5e92-4901-acc9-576b534e1c0d): INSERT INTO TABLE fraud_detections
[2025-03-20T10:34:45.706+0000] {subprocess.py:93} INFO -     SELECT
[2025-03-20T10:34:45.707+0000] {subprocess.py:93} INFO -         t.transaction_id,
[2025-03-20T10:34:45.708+0000] {subprocess.py:93} INFO -         t.date_time,
[2025-03-20T10:34:45.708+0000] {subprocess.py:93} INFO -         t.amount,
[2025-03-20T10:34:45.709+0000] {subprocess.py:93} INFO -         t.customer_id,
[2025-03-20T10:34:45.710+0000] {subprocess.py:93} INFO -         t.location,
[2025-03-20T10:34:45.712+0000] {subprocess.py:93} INFO -         'High Amount' AS fraud_reason
[2025-03-20T10:34:45.714+0000] {subprocess.py:93} INFO -     FROM transactions t
[2025-03-20T10:34:45.716+0000] {subprocess.py:93} INFO -     WHERE t.batch_id = 'batch_0'
[2025-03-20T10:34:45.717+0000] {subprocess.py:93} INFO -     AND t.amount > 1000
[2025-03-20T10:34:45.718+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:45.718+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-20T10:34:45.719+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:t.transaction_id, type:string, comment:null), FieldSchema(name:t.date_time, type:string, comment:null), FieldSchema(name:t.amount, type:double, comment:null), FieldSchema(name:t.customer_id, type:string, comment:null), FieldSchema(name:t.location, type:string, comment:null), FieldSchema(name:fraud_reason, type:string, comment:null)], properties:null)
[2025-03-20T10:34:45.719+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250320103444_4cf7616b-5e92-4901-acc9-576b534e1c0d); Time taken: 0.301 seconds
[2025-03-20T10:34:45.720+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:45.720+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250320103444_4cf7616b-5e92-4901-acc9-576b534e1c0d): INSERT INTO TABLE fraud_detections
[2025-03-20T10:34:45.720+0000] {subprocess.py:93} INFO -     SELECT
[2025-03-20T10:34:45.721+0000] {subprocess.py:93} INFO -         t.transaction_id,
[2025-03-20T10:34:45.721+0000] {subprocess.py:93} INFO -         t.date_time,
[2025-03-20T10:34:45.721+0000] {subprocess.py:93} INFO -         t.amount,
[2025-03-20T10:34:45.721+0000] {subprocess.py:93} INFO -         t.customer_id,
[2025-03-20T10:34:45.722+0000] {subprocess.py:93} INFO -         t.location,
[2025-03-20T10:34:45.722+0000] {subprocess.py:93} INFO -         'High Amount' AS fraud_reason
[2025-03-20T10:34:45.722+0000] {subprocess.py:93} INFO -     FROM transactions t
[2025-03-20T10:34:45.723+0000] {subprocess.py:93} INFO -     WHERE t.batch_id = 'batch_0'
[2025-03-20T10:34:45.723+0000] {subprocess.py:93} INFO -     AND t.amount > 1000
[2025-03-20T10:34:45.723+0000] {subprocess.py:93} INFO - INFO  : Query ID = root_20250320103444_4cf7616b-5e92-4901-acc9-576b534e1c0d
[2025-03-20T10:34:45.723+0000] {subprocess.py:93} INFO - INFO  : Total jobs = 1
[2025-03-20T10:34:45.724+0000] {subprocess.py:93} INFO - INFO  : Launching Job 1 out of 1
[2025-03-20T10:34:45.724+0000] {subprocess.py:93} INFO - INFO  : Starting task [Stage-1:MAPRED] in serial mode
[2025-03-20T10:34:54.791+0000] {subprocess.py:93} INFO - ERROR : Failed to monitor Job[-1] with exception 'java.lang.IllegalStateException(Connection to remote Spark driver was lost)' Last known state = SENT
[2025-03-20T10:34:54.793+0000] {subprocess.py:93} INFO - java.lang.IllegalStateException: Connection to remote Spark driver was lost
[2025-03-20T10:34:54.794+0000] {subprocess.py:93} INFO - 	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
[2025-03-20T10:34:54.795+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.spark.status.RemoteSparkJobMonitor.startMonitor(RemoteSparkJobMonitor.java:70)
[2025-03-20T10:34:54.795+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.spark.status.impl.RemoteSparkJobRef.monitorJob(RemoteSparkJobRef.java:60)
[2025-03-20T10:34:54.796+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.spark.SparkTask.execute(SparkTask.java:146)
[2025-03-20T10:34:54.797+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:205)
[2025-03-20T10:34:54.797+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:97)
[2025-03-20T10:34:54.798+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2664)
[2025-03-20T10:34:54.799+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:2335)
[2025-03-20T10:34:54.801+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:2011)
[2025-03-20T10:34:54.802+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1709)
[2025-03-20T10:34:54.803+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1703)
[2025-03-20T10:34:54.804+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:157)
[2025-03-20T10:34:54.805+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:224)
[2025-03-20T10:34:54.806+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation.access$700(SQLOperation.java:87)
[2025-03-20T10:34:54.806+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:316)
[2025-03-20T10:34:54.807+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-20T10:34:54.809+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-20T10:34:54.809+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-20T10:34:54.810+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:329)
[2025-03-20T10:34:54.813+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-03-20T10:34:54.815+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-03-20T10:34:54.820+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-20T10:34:54.822+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-20T10:34:54.823+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-20T10:34:54.824+0000] {subprocess.py:93} INFO - 
[2025-03-20T10:34:54.826+0000] {subprocess.py:93} INFO - ERROR : FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.spark.SparkTask. RPC channel is closed.
[2025-03-20T10:34:54.827+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250320103444_4cf7616b-5e92-4901-acc9-576b534e1c0d); Time taken: 10.08 seconds
[2025-03-20T10:34:54.827+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-20T10:34:54.828+0000] {subprocess.py:93} INFO - Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.spark.SparkTask. RPC channel is closed. (state=08S01,code=1)
[2025-03-20T10:34:54.835+0000] {subprocess.py:93} INFO - Closing: 0: jdbc:hive2://localhost:10000
[2025-03-20T10:34:54.928+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-20T10:34:54.945+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-20T10:34:54.953+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=detect_fraud, execution_date=20250320T103426, start_date=20250320T103441, end_date=20250320T103454
[2025-03-20T10:34:54.979+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 255 for task detect_fraud (Bash command failed. The command returned a non-zero exit code 1.; 491)
[2025-03-20T10:34:55.035+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-20T10:34:55.056+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
