[2025-03-21T13:34:27.945+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 manual__2025-03-21T13:31:53.143260+00:00 [queued]>
[2025-03-21T13:34:27.960+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 manual__2025-03-21T13:31:53.143260+00:00 [queued]>
[2025-03-21T13:34:27.964+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:34:28.002+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud_batch_20250321_131625> on 2025-03-21 13:31:53.143260+00:00
[2025-03-21T13:34:28.011+0000] {standard_task_runner.py:57} INFO - Started process 2774 to run task
[2025-03-21T13:34:28.016+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud_batch_20250321_131625', 'manual__2025-03-21T13:31:53.143260+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpx6zkwc9y']
[2025-03-21T13:34:28.019+0000] {standard_task_runner.py:85} INFO - Job 653: Subtask detect_fraud_batch_20250321_131625
[2025-03-21T13:34:28.121+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 manual__2025-03-21T13:31:53.143260+00:00 [running]> on host 1b7c3466167a
[2025-03-21T13:34:28.273+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud_batch_20250321_131625' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:31:53.143260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:31:53.143260+00:00'
[2025-03-21T13:34:28.280+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:34:28.292+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive spark-submit --master spark://localhost:7077 /hive/scripts/detect_fraud.py "batch_20250321_131625"\n            ']
[2025-03-21T13:34:28.337+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:34:54.353+0000] {subprocess.py:93} INFO - 25/03/21 13:34:54 INFO SparkContext: Running Spark version 3.5.0
[2025-03-21T13:34:54.436+0000] {subprocess.py:93} INFO - 25/03/21 13:34:54 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-21T13:34:54.439+0000] {subprocess.py:93} INFO - 25/03/21 13:34:54 INFO SparkContext: Java version 1.8.0_342
[2025-03-21T13:34:55.565+0000] {subprocess.py:93} INFO - 25/03/21 13:34:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-21T13:34:57.544+0000] {subprocess.py:93} INFO - 25/03/21 13:34:57 INFO ResourceUtils: ==============================================================
[2025-03-21T13:34:57.551+0000] {subprocess.py:93} INFO - 25/03/21 13:34:57 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-21T13:34:57.553+0000] {subprocess.py:93} INFO - 25/03/21 13:34:57 INFO ResourceUtils: ==============================================================
[2025-03-21T13:34:57.554+0000] {subprocess.py:93} INFO - 25/03/21 13:34:57 INFO SparkContext: Submitted application: FraudDetection
[2025-03-21T13:34:58.649+0000] {subprocess.py:93} INFO - 25/03/21 13:34:58 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-21T13:34:59.048+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO ResourceProfile: Limiting resource is cpu
[2025-03-21T13:34:59.049+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-21T13:34:59.851+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO SecurityManager: Changing view acls to: root
[2025-03-21T13:34:59.854+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO SecurityManager: Changing modify acls to: root
[2025-03-21T13:34:59.856+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO SecurityManager: Changing view acls groups to:
[2025-03-21T13:34:59.858+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO SecurityManager: Changing modify acls groups to:
[2025-03-21T13:34:59.859+0000] {subprocess.py:93} INFO - 25/03/21 13:34:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root; groups with view permissions: EMPTY; users with modify permissions: root; groups with modify permissions: EMPTY
[2025-03-21T13:35:02.939+0000] {subprocess.py:93} INFO - 25/03/21 13:35:02 INFO Utils: Successfully started service 'sparkDriver' on port 44423.
[2025-03-21T13:35:03.252+0000] {subprocess.py:93} INFO - 25/03/21 13:35:03 INFO SparkEnv: Registering MapOutputTracker
[2025-03-21T13:35:03.638+0000] {subprocess.py:93} INFO - 25/03/21 13:35:03 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-21T13:35:03.851+0000] {subprocess.py:93} INFO - 25/03/21 13:35:03 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-21T13:35:03.853+0000] {subprocess.py:93} INFO - 25/03/21 13:35:03 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-21T13:35:03.953+0000] {subprocess.py:93} INFO - 25/03/21 13:35:03 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-21T13:35:05.245+0000] {subprocess.py:93} INFO - 25/03/21 13:35:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-517b4a36-3582-4d3d-9650-de66e62e17e7
[2025-03-21T13:35:05.845+0000] {subprocess.py:93} INFO - 25/03/21 13:35:05 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
[2025-03-21T13:35:06.355+0000] {subprocess.py:93} INFO - 25/03/21 13:35:06 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-21T13:35:10.120+0000] {subprocess.py:93} INFO - 25/03/21 13:35:10 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-21T13:35:13.109+0000] {subprocess.py:93} INFO - 25/03/21 13:35:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-21T13:35:15.315+0000] {subprocess.py:93} INFO - 25/03/21 13:35:15 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2025-03-21T13:35:16.210+0000] {subprocess.py:93} INFO - 25/03/21 13:35:16 INFO TransportClientFactory: Successfully created connection to localhost/127.0.0.1:7077 after 677 ms (0 ms spent in bootstraps)
[2025-03-21T13:35:19.005+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250321133518-0010
[2025-03-21T13:35:19.398+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38517.
[2025-03-21T13:35:19.401+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO NettyBlockTransferService: Server created on e3006a54eed1:38517
[2025-03-21T13:35:19.406+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-21T13:35:19.420+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250321133518-0010/0 on worker-20250321124806-172.18.0.2-46237 (172.18.0.2:46237) with 2 core(s)
[2025-03-21T13:35:19.608+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO StandaloneSchedulerBackend: Granted executor ID app-20250321133518-0010/0 on hostPort 172.18.0.2:46237 with 2 core(s), 1024.0 MiB RAM
[2025-03-21T13:35:19.620+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e3006a54eed1, 38517, None)
[2025-03-21T13:35:19.717+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO BlockManagerMasterEndpoint: Registering block manager e3006a54eed1:38517 with 366.3 MiB RAM, BlockManagerId(driver, e3006a54eed1, 38517, None)
[2025-03-21T13:35:19.795+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e3006a54eed1, 38517, None)
[2025-03-21T13:35:19.802+0000] {subprocess.py:93} INFO - 25/03/21 13:35:19 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e3006a54eed1, 38517, None)
[2025-03-21T13:35:21.902+0000] {subprocess.py:93} INFO - 25/03/21 13:35:21 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250321133518-0010/0 is now RUNNING
[2025-03-21T13:35:26.214+0000] {subprocess.py:93} INFO - 25/03/21 13:35:26 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-21T13:35:31.818+0000] {subprocess.py:93} INFO - Spark version: 3.5.0
[2025-03-21T13:35:34.305+0000] {subprocess.py:93} INFO - 25/03/21 13:35:34 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-21T13:35:46.966+0000] {subprocess.py:93} INFO - 25/03/21 13:35:46 INFO SharedState: Warehouse path is 'hdfs://localhost:9000/data/warehouse'.
[2025-03-21T13:36:16.208+0000] {subprocess.py:93} INFO - 25/03/21 13:36:16 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.2:44136) with ID 0,  ResourceProfileId 0
[2025-03-21T13:36:18.541+0000] {subprocess.py:93} INFO - 25/03/21 13:36:18 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.2:33311 with 366.3 MiB RAM, BlockManagerId(0, 172.18.0.2, 33311, None)
[2025-03-21T13:36:19.009+0000] {subprocess.py:93} INFO - 25/03/21 13:36:18 INFO InMemoryFileIndex: It took 1190 ms to list leaf files for 1 paths.
[2025-03-21T13:36:28.923+0000] {subprocess.py:93} INFO - 25/03/21 13:36:28 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
[2025-03-21T13:36:30.015+0000] {subprocess.py:93} INFO - 25/03/21 13:36:29 INFO DAGScheduler: Got job 0 (parquet at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-21T13:36:30.016+0000] {subprocess.py:93} INFO - 25/03/21 13:36:30 INFO DAGScheduler: Final stage: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0)
[2025-03-21T13:36:30.017+0000] {subprocess.py:93} INFO - 25/03/21 13:36:30 INFO DAGScheduler: Parents of final stage: List()
[2025-03-21T13:36:30.032+0000] {subprocess.py:93} INFO - 25/03/21 13:36:30 INFO DAGScheduler: Missing parents: List()
[2025-03-21T13:36:30.431+0000] {subprocess.py:93} INFO - 25/03/21 13:36:30 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-21T13:36:32.636+0000] {subprocess.py:93} INFO - 25/03/21 13:36:32 INFO AsyncEventQueue: Process of event SparkListenerJobStart(0,1742564190096,WrappedArray(org.apache.spark.scheduler.StageInfo@442ead3),{spark.rdd.scope.noOverride=true, spark.rdd.scope={"id":"2","name":"collect"}}) by listener AppStatusListener took 2.019376838s.
[2025-03-21T13:36:33.829+0000] {subprocess.py:93} INFO - 25/03/21 13:36:33 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 103.3 KiB, free 366.2 MiB)
[2025-03-21T13:36:36.517+0000] {subprocess.py:93} INFO - 25/03/21 13:36:36 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 37.2 KiB, free 366.2 MiB)
[2025-03-21T13:36:36.046+0000] {subprocess.py:93} INFO - 25/03/21 13:36:36 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on e3006a54eed1:38517 (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:36:35.392+0000] {subprocess.py:93} INFO - 25/03/21 13:36:35 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1580
[2025-03-21T13:36:36.093+0000] {subprocess.py:93} INFO - 25/03/21 13:36:36 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-21T13:36:36.184+0000] {subprocess.py:93} INFO - 25/03/21 13:36:36 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-21T13:36:37.604+0000] {subprocess.py:93} INFO - 25/03/21 13:36:37 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.2, executor 0, partition 0, PROCESS_LOCAL, 7831 bytes)
[2025-03-21T13:36:40.436+0000] {subprocess.py:93} INFO - 25/03/21 13:36:40 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.2:33311 (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:37:04.979+0000] {subprocess.py:93} INFO - 25/03/21 13:37:04 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 27706 ms on 172.18.0.2 (executor 0) (1/1)
[2025-03-21T13:37:05.015+0000] {subprocess.py:93} INFO - 25/03/21 13:37:04 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-21T13:37:05.099+0000] {subprocess.py:93} INFO - 25/03/21 13:37:05 INFO DAGScheduler: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0) finished in 33.861 s
[2025-03-21T13:37:05.192+0000] {subprocess.py:93} INFO - 25/03/21 13:37:05 INFO DAGScheduler: Job 0 is finished. Cancelling potential speculative or zombie tasks for this job
[2025-03-21T13:37:05.198+0000] {subprocess.py:93} INFO - 25/03/21 13:37:05 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage finished
[2025-03-21T13:37:05.235+0000] {subprocess.py:93} INFO - 25/03/21 13:37:05 INFO DAGScheduler: Job 0 finished: parquet at NativeMethodAccessorImpl.java:0, took 37.613605 s
[2025-03-21T13:37:07.079+0000] {subprocess.py:93} INFO - 25/03/21 13:37:07 INFO BlockManagerInfo: Removed broadcast_0_piece0 on e3006a54eed1:38517 in memory (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:37:07.192+0000] {subprocess.py:93} INFO - 25/03/21 13:37:07 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 172.18.0.2:33311 in memory (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:37:15.675+0000] {subprocess.py:93} INFO - 25/03/21 13:37:15 INFO FileSourceStrategy: Pushed Filters: IsNotNull(amount),GreaterThan(amount,1000.0)
[2025-03-21T13:37:15.712+0000] {subprocess.py:93} INFO - 25/03/21 13:37:15 INFO FileSourceStrategy: Post-Scan Filters: isnotnull(amount#2),(amount#2 > 1000.0)
[2025-03-21T13:37:17.359+0000] {subprocess.py:93} INFO - 25/03/21 13:37:17 INFO ParquetUtils: Using default output committer for Parquet: org.apache.parquet.hadoop.ParquetOutputCommitter
[2025-03-21T13:37:18.037+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO FileOutputCommitter: File Output Committer Algorithm version is 1
[2025-03-21T13:37:18.038+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-03-21T13:37:18.090+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO SQLHadoopMapReduceCommitProtocol: Using user defined output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
[2025-03-21T13:37:18.117+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO FileOutputCommitter: File Output Committer Algorithm version is 1
[2025-03-21T13:37:18.119+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-03-21T13:37:18.247+0000] {subprocess.py:93} INFO - 25/03/21 13:37:18 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
[2025-03-21T13:37:34.523+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO CodeGenerator: Code generated in 700.878817 ms
[2025-03-21T13:37:34.565+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 357.5 KiB, free 366.0 MiB)
[2025-03-21T13:37:34.591+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 35.2 KiB, free 365.9 MiB)
[2025-03-21T13:37:34.593+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on e3006a54eed1:38517 (size: 35.2 KiB, free: 366.3 MiB)
[2025-03-21T13:37:34.597+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO SparkContext: Created broadcast 1 from parquet at NativeMethodAccessorImpl.java:0
[2025-03-21T13:37:34.653+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4194304 bytes, open cost is considered as scanning 4194304 bytes.
[2025-03-21T13:37:34.860+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
[2025-03-21T13:37:34.864+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO DAGScheduler: Got job 1 (parquet at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-21T13:37:34.865+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO DAGScheduler: Final stage: ResultStage 1 (parquet at NativeMethodAccessorImpl.java:0)
[2025-03-21T13:37:34.865+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO DAGScheduler: Parents of final stage: List()
[2025-03-21T13:37:34.866+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO DAGScheduler: Missing parents: List()
[2025-03-21T13:37:34.869+0000] {subprocess.py:93} INFO - 25/03/21 13:37:34 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[5] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-21T13:37:36.168+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 219.2 KiB, free 365.7 MiB)
[2025-03-21T13:37:36.201+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 77.5 KiB, free 365.6 MiB)
[2025-03-21T13:37:36.209+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on e3006a54eed1:38517 (size: 77.5 KiB, free: 366.2 MiB)
[2025-03-21T13:37:36.216+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1580
[2025-03-21T13:37:36.220+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[5] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-21T13:37:36.224+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks resource profile 0
[2025-03-21T13:37:36.438+0000] {subprocess.py:93} INFO - 25/03/21 13:37:36 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1) (172.18.0.2, executor 0, partition 0, ANY, 8299 bytes)
[2025-03-21T13:37:39.133+0000] {subprocess.py:93} INFO - 25/03/21 13:37:39 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 172.18.0.2:33311 (size: 77.5 KiB, free: 366.2 MiB)
[2025-03-21T13:37:56.105+0000] {subprocess.py:97} INFO - Command exited with return code 137
[2025-03-21T13:37:56.325+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 137.
[2025-03-21T13:37:56.401+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=detect_fraud_batch_20250321_131625, execution_date=20250321T133153, start_date=20250321T133427, end_date=20250321T133756
[2025-03-21T13:37:56.589+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-21T13:37:56.593+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:37:56.593+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:37:56.617+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:37:56.618+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:37:56.620+0000] {taskinstance.py:2005} ERROR - Failed to send email to: rabiizahnoune7@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 137.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-21T13:37:56.678+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:37:56.680+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:37:56.683+0000] {taskinstance.py:1703} ERROR - Error when executing on_failure_callback callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 137.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1700, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/fraud_detection_pipeline.py", line 27, in on_failure_callback
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-21T13:37:56.762+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 653 for task detect_fraud_batch_20250321_131625 (Bash command failed. The command returned a non-zero exit code 137.; 2774)
[2025-03-21T13:37:56.830+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T13:37:56.977+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
