[2025-03-19T17:38:52.521+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T17:38:35.899311+00:00 [queued]>
[2025-03-19T17:38:52.540+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T17:38:35.899311+00:00 [queued]>
[2025-03-19T17:38:52.541+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-19T17:38:52.570+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud> on 2025-03-19 17:38:35.899311+00:00
[2025-03-19T17:38:52.580+0000] {standard_task_runner.py:57} INFO - Started process 1353 to run task
[2025-03-19T17:38:52.585+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud', 'manual__2025-03-19T17:38:35.899311+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpggvntcrk']
[2025-03-19T17:38:52.589+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask detect_fraud
[2025-03-19T17:38:52.683+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T17:38:35.899311+00:00 [running]> on host 347688f31140
[2025-03-19T17:38:52.763+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-19T17:38:52.819+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T17:38:35.899311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T17:38:35.899311+00:00'
[2025-03-19T17:38:52.822+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T17:38:52.825+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    docker exec hive beeline -u "jdbc:hive2://localhost:10000" -e "\n    CREATE TABLE IF NOT EXISTS fraud_detections (\n        transaction_id STRING,\n        date_time STRING,\n        amount DOUBLE,\n        customer_id STRING,\n        location STRING,\n        fraud_reason STRING\n    )\n    STORED AS PARQUET\n    LOCATION \'/data/fraud_detections\';\n    INSERT INTO TABLE fraud_detections\n    WITH transaction_counts AS (\n        SELECT\n            t.transaction_id,\n            t.date_time,\n            t.amount,\n            t.customer_id,\n            t.location,\n            t.merchant_details,\n            COUNT(*) OVER (PARTITION BY t.customer_id) AS transaction_count\n        FROM transactions t\n        WHERE t.batch_id = \'batch_20250319_173835\'\n    )\n    SELECT\n        t.transaction_id,\n        t.date_time,\n        t.amount,\n        t.customer_id,\n        t.location,\n        CASE\n            WHEN t.amount > 1000 THEN \'High Amount\'\n            WHEN t.transaction_count > 10 THEN \'High Frequency\'\n            WHEN t.location NOT IN (\'City1\', \'City2\', \'City3\') THEN \'Unusual Location\'\n            WHEN t.merchant_details LIKE \'%fraud%\' THEN \'Suspicious Merchant\'\n        END AS fraud_reason\n    FROM transaction_counts t\n    WHERE t.batch_id = \'batch_20250319_173835\'\n    HAVING fraud_reason IS NOT NULL;"\n    ']
[2025-03-19T17:38:52.842+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T17:38:54.061+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-19T17:38:54.062+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T17:38:54.064+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T17:38:54.064+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-19T17:38:54.331+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-19T17:38:55.389+0000] {subprocess.py:93} INFO - Connecting to jdbc:hive2://localhost:10000
[2025-03-19T17:38:55.644+0000] {subprocess.py:93} INFO - Connected to: Apache Hive (version 3.1.3)
[2025-03-19T17:38:55.645+0000] {subprocess.py:93} INFO - Driver: Hive JDBC (version 3.1.3)
[2025-03-19T17:38:55.647+0000] {subprocess.py:93} INFO - Transaction isolation: TRANSACTION_REPEATABLE_READ
[2025-03-19T17:38:55.766+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250319173855_681f6758-4758-4561-882d-b9e0dc9cb8dd): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T17:38:55.767+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T17:38:55.768+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T17:38:55.769+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T17:38:55.770+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T17:38:55.770+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T17:38:55.772+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T17:38:55.773+0000] {subprocess.py:93} INFO -     )
[2025-03-19T17:38:55.774+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T17:38:55.775+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-19T17:38:55.776+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:38:55.776+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-19T17:38:55.777+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
[2025-03-19T17:38:55.778+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250319173855_681f6758-4758-4561-882d-b9e0dc9cb8dd); Time taken: 0.005 seconds
[2025-03-19T17:38:55.778+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:38:55.779+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250319173855_681f6758-4758-4561-882d-b9e0dc9cb8dd): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T17:38:55.780+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T17:38:55.780+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T17:38:55.781+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T17:38:55.782+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T17:38:55.783+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T17:38:55.783+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T17:38:55.784+0000] {subprocess.py:93} INFO -     )
[2025-03-19T17:38:55.784+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T17:38:55.785+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-19T17:38:55.786+0000] {subprocess.py:93} INFO - INFO  : Starting task [Stage-0:DDL] in serial mode
[2025-03-19T17:38:55.786+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250319173855_681f6758-4758-4561-882d-b9e0dc9cb8dd); Time taken: 0.045 seconds
[2025-03-19T17:38:55.787+0000] {subprocess.py:93} INFO - INFO  : OK
[2025-03-19T17:38:55.788+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:38:55.788+0000] {subprocess.py:93} INFO - No rows affected (0.106 seconds)
[2025-03-19T17:38:55.798+0000] {subprocess.py:93} INFO - Error: Error while compiling statement: FAILED: ParseException line 2:4 cannot recognize input near 'WITH' 'transaction_counts' 'AS' in statement (state=42000,code=40000)
[2025-03-19T17:38:55.803+0000] {subprocess.py:93} INFO - Closing: 0: jdbc:hive2://localhost:10000
[2025-03-19T17:38:55.846+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T17:38:55.858+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T17:38:55.865+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=detect_fraud, execution_date=20250319T173835, start_date=20250319T173852, end_date=20250319T173855
[2025-03-19T17:38:55.882+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task detect_fraud (Bash command failed. The command returned a non-zero exit code 1.; 1353)
[2025-03-19T17:38:55.899+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T17:38:55.924+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
