[2025-03-21T13:32:48.083+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131546 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.141+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131546 scheduled__2025-03-21T13:27:39.231672+00:00 [queued]>
[2025-03-21T13:32:48.144+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:32:48.318+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs_batch_20250321_131546> on 2025-03-21 13:27:39.231672+00:00
[2025-03-21T13:32:48.338+0000] {standard_task_runner.py:57} INFO - Started process 2334 to run task
[2025-03-21T13:32:48.348+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs_batch_20250321_131546', 'scheduled__2025-03-21T13:27:39.231672+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpxc7pm4m5']
[2025-03-21T13:32:48.372+0000] {standard_task_runner.py:85} INFO - Job 633: Subtask copy_to_hdfs_batch_20250321_131546
[2025-03-21T13:32:48.656+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250321_131546 scheduled__2025-03-21T13:27:39.231672+00:00 [running]> on host 1b7c3466167a
[2025-03-21T13:32:49.177+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs_batch_20250321_131546' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:27:39.231672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T13:27:39.231672+00:00'
[2025-03-21T13:32:49.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:32:49.197+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_20250321_131546 &&             docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_20250321_131546.parquet /data/transactions/transactions_batch_20250321_131546/\n            ']
[2025-03-21T13:32:49.413+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:33:03.525+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-21T13:33:03.534+0000] {process_utils.py:131} INFO - Sending 15 to group 2334. PIDs of all processes in the group: [2349, 2376, 2334]
[2025-03-21T13:33:03.536+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2334
[2025-03-21T13:33:03.538+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T13:33:03.540+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T13:33:03.548+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2376, status='terminated', started='13:32:49') (2376) terminated with exit code None
[2025-03-21T13:33:03.692+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2349, status='terminated', started='13:32:49') (2349) terminated with exit code None
[2025-03-21T13:33:03.704+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2334, status='terminated', exitcode=0, started='13:32:48') (2334) terminated with exit code 0
