[2025-03-20T11:23:20.187+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T10:33:15.476240+00:00 [queued]>
[2025-03-20T11:23:20.197+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T10:33:15.476240+00:00 [queued]>
[2025-03-20T11:23:20.198+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-20T11:23:20.212+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs> on 2025-03-20 10:33:15.476240+00:00
[2025-03-20T11:23:20.218+0000] {standard_task_runner.py:57} INFO - Started process 251 to run task
[2025-03-20T11:23:20.221+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs', 'scheduled__2025-03-20T10:33:15.476240+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpr9v633be']
[2025-03-20T11:23:20.225+0000] {standard_task_runner.py:85} INFO - Job 269: Subtask copy_to_hdfs
[2025-03-20T11:23:20.281+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T10:33:15.476240+00:00 [running]> on host 4365db940d3f
[2025-03-20T11:23:20.396+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T10:33:15.476240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T10:33:15.476240+00:00'
[2025-03-20T11:23:20.398+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-20T11:23:20.399+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_0 && docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_0.parquet /data/transactions/transactions_batch_0/']
[2025-03-20T11:23:20.409+0000] {subprocess.py:86} INFO - Output:
[2025-03-20T11:23:20.449+0000] {subprocess.py:93} INFO - Error response from daemon: container c74c10df9e5d71be59a37970a66edd1d341f9d1a5ff52fccdaf9f4e864836369 is not running
[2025-03-20T11:23:20.452+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-20T11:23:20.464+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-20T11:23:20.469+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=copy_to_hdfs, execution_date=20250320T103315, start_date=20250320T112320, end_date=20250320T112320
[2025-03-20T11:23:20.483+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 269 for task copy_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 251)
[2025-03-20T11:23:20.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-20T11:23:20.540+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
