[2025-03-21T12:57:00.394+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_144447 manual__2025-03-21T12:56:48.947688+00:00 [queued]>
[2025-03-21T12:57:00.419+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_144447 manual__2025-03-21T12:56:48.947688+00:00 [queued]>
[2025-03-21T12:57:00.420+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T12:57:00.463+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs_batch_20250320_144447> on 2025-03-21 12:56:48.947688+00:00
[2025-03-21T12:57:00.474+0000] {standard_task_runner.py:57} INFO - Started process 981 to run task
[2025-03-21T12:57:00.487+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs_batch_20250320_144447', 'manual__2025-03-21T12:56:48.947688+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp38tds_6f']
[2025-03-21T12:57:00.493+0000] {standard_task_runner.py:85} INFO - Job 551: Subtask copy_to_hdfs_batch_20250320_144447
[2025-03-21T12:57:00.631+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_144447 manual__2025-03-21T12:56:48.947688+00:00 [running]> on host 1b7c3466167a
[2025-03-21T12:57:00.800+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs_batch_20250320_144447' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T12:56:48.947688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T12:56:48.947688+00:00'
[2025-03-21T12:57:00.804+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T12:57:00.805+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_20250320_144447 &&             docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_20250320_144447.parquet /data/transactions/transactions_batch_20250320_144447/\n            ']
[2025-03-21T12:57:00.832+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T12:57:15.914+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-21T12:57:15.928+0000] {process_utils.py:131} INFO - Sending 15 to group 981. PIDs of all processes in the group: [986, 989, 981]
[2025-03-21T12:57:15.929+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 981
[2025-03-21T12:57:15.930+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T12:57:15.931+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T12:57:15.989+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=981, status='terminated', exitcode=0, started='12:56:59') (981) terminated with exit code 0
[2025-03-21T12:57:15.993+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=986, status='terminated', started='12:57:00') (986) terminated with exit code None
[2025-03-21T12:57:15.995+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=989, status='terminated', started='12:57:00') (989) terminated with exit code None
