[2025-03-21T12:57:00.396+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_135205 manual__2025-03-21T12:56:48.947688+00:00 [queued]>
[2025-03-21T12:57:00.423+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_135205 manual__2025-03-21T12:56:48.947688+00:00 [queued]>
[2025-03-21T12:57:00.425+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T12:57:00.472+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs_batch_20250320_135205> on 2025-03-21 12:56:48.947688+00:00
[2025-03-21T12:57:00.488+0000] {standard_task_runner.py:57} INFO - Started process 983 to run task
[2025-03-21T12:57:00.498+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs_batch_20250320_135205', 'manual__2025-03-21T12:56:48.947688+00:00', '--job-id', '549', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp81ldz4x5']
[2025-03-21T12:57:00.505+0000] {standard_task_runner.py:85} INFO - Job 549: Subtask copy_to_hdfs_batch_20250320_135205
[2025-03-21T12:57:00.637+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs_batch_20250320_135205 manual__2025-03-21T12:56:48.947688+00:00 [running]> on host 1b7c3466167a
[2025-03-21T12:57:00.800+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs_batch_20250320_135205' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T12:56:48.947688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T12:56:48.947688+00:00'
[2025-03-21T12:57:00.804+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T12:57:00.806+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_20250320_135205 &&             docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_20250320_135205.parquet /data/transactions/transactions_batch_20250320_135205/\n            ']
[2025-03-21T12:57:00.831+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T12:57:15.891+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-21T12:57:15.900+0000] {process_utils.py:131} INFO - Sending 15 to group 983. PIDs of all processes in the group: [985, 990, 983]
[2025-03-21T12:57:15.901+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 983
[2025-03-21T12:57:15.905+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T12:57:15.906+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T12:57:16.004+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=983, status='terminated', exitcode=0, started='12:56:59') (983) terminated with exit code 0
[2025-03-21T12:57:16.010+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=990, status='terminated', started='12:57:00') (990) terminated with exit code None
[2025-03-21T12:57:16.012+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=985, status='terminated', started='12:57:00') (985) terminated with exit code None
