[2025-03-20T12:51:25.497+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.transfer_from_kafka manual__2025-03-20T12:51:21.105331+00:00 [queued]>
[2025-03-20T12:51:25.512+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.transfer_from_kafka manual__2025-03-20T12:51:21.105331+00:00 [queued]>
[2025-03-20T12:51:25.515+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-20T12:51:25.537+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): transfer_from_kafka> on 2025-03-20 12:51:21.105331+00:00
[2025-03-20T12:51:25.544+0000] {standard_task_runner.py:57} INFO - Started process 909 to run task
[2025-03-20T12:51:25.550+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'transfer_from_kafka', 'manual__2025-03-20T12:51:21.105331+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpa34mo95g']
[2025-03-20T12:51:25.553+0000] {standard_task_runner.py:85} INFO - Job 301: Subtask transfer_from_kafka
[2025-03-20T12:51:25.646+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.transfer_from_kafka manual__2025-03-20T12:51:21.105331+00:00 [running]> on host 3938a1dd8bd9
[2025-03-20T12:51:25.764+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='transfer_from_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T12:51:21.105331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T12:51:21.105331+00:00'
[2025-03-20T12:51:25.766+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-20T12:51:25.768+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp kafka:/data/transactions/transactions_batch_batch_20250320_124846.parquet hive:/data/transactions/']
[2025-03-20T12:51:25.784+0000] {subprocess.py:86} INFO - Output:
[2025-03-20T12:51:25.823+0000] {subprocess.py:93} INFO - copying between containers is not supported
[2025-03-20T12:51:25.824+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-20T12:51:25.840+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-20T12:51:25.846+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=transfer_from_kafka, execution_date=20250320T125121, start_date=20250320T125125, end_date=20250320T125125
[2025-03-20T12:51:25.866+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 301 for task transfer_from_kafka (Bash command failed. The command returned a non-zero exit code 1.; 909)
[2025-03-20T12:51:25.884+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-20T12:51:25.918+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
