[2025-03-19T17:21:35.036+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud scheduled__2025-03-19T17:16:13.237024+00:00 [queued]>
[2025-03-19T17:21:35.059+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud scheduled__2025-03-19T17:16:13.237024+00:00 [queued]>
[2025-03-19T17:21:35.060+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-19T17:21:35.111+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud> on 2025-03-19 17:16:13.237024+00:00
[2025-03-19T17:21:35.129+0000] {standard_task_runner.py:57} INFO - Started process 436 to run task
[2025-03-19T17:21:35.137+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud', 'scheduled__2025-03-19T17:16:13.237024+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpbfm2q7nq']
[2025-03-19T17:21:35.156+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask detect_fraud
[2025-03-19T17:21:35.276+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud scheduled__2025-03-19T17:16:13.237024+00:00 [running]> on host 347688f31140
[2025-03-19T17:21:35.356+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-19T17:21:35.402+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T17:16:13.237024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T17:16:13.237024+00:00'
[2025-03-19T17:21:35.408+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T17:21:35.409+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    docker exec hive beeline -u "jdbc:hive2://localhost:10000" -e "\n    CREATE TABLE IF NOT EXISTS fraud_detections (\n        transaction_id STRING,\n        date_time STRING,\n        amount DOUBLE,\n        customer_id STRING,\n        location STRING,\n        fraud_reason STRING\n    )\n    STORED AS PARQUET;\n    INSERT INTO TABLE fraud_detections\n    SELECT\n        t.transaction_id,\n        t.date_time,\n        t.amount,\n        t.customer_id,\n        t.location,\n        CASE\n            WHEN t.amount > 1000 THEN \'High Amount\'\n            WHEN COUNT(*) OVER (PARTITION BY t.customer_id ORDER BY t.date_time RANGE BETWEEN INTERVAL \'1\' HOUR PRECEDING AND CURRENT ROW) > 10 THEN \'High Frequency\'\n            WHEN t.location NOT IN (\'City1\', \'City2\', \'City3\') THEN \'Unusual Location\'\n            WHEN t.merchant_details IN (SELECT merchant_id FROM blacklist) THEN \'Blacklisted Merchant\'\n            WHEN fr.fraud_count > 3 THEN \'High Fraud History\'\n        END AS fraud_reason\n    FROM transactions t\n    LEFT JOIN fraud_reports fr ON t.customer_id = fr.customer_id\n    WHERE t.batch_id = \'batch_20250319_171613\'\n    HAVING fraud_reason IS NOT NULL;"\n    ']
[2025-03-19T17:21:35.427+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T17:21:36.997+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-19T17:21:36.998+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T17:21:36.999+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T17:21:37.000+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-19T17:21:37.563+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-19T17:21:39.556+0000] {subprocess.py:93} INFO - Connecting to jdbc:hive2://localhost:10000
[2025-03-19T17:21:40.013+0000] {subprocess.py:93} INFO - Connected to: Apache Hive (version 3.1.3)
[2025-03-19T17:21:40.014+0000] {subprocess.py:93} INFO - Driver: Hive JDBC (version 3.1.3)
[2025-03-19T17:21:40.015+0000] {subprocess.py:93} INFO - Transaction isolation: TRANSACTION_REPEATABLE_READ
[2025-03-19T17:21:40.146+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250319172140_ef1d8949-4f5b-47af-bc58-ece6c16ac550): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T17:21:40.148+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T17:21:40.149+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T17:21:40.151+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T17:21:40.151+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T17:21:40.152+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T17:21:40.153+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T17:21:40.154+0000] {subprocess.py:93} INFO -     )
[2025-03-19T17:21:40.155+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T17:21:40.156+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:21:40.157+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-19T17:21:40.157+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
[2025-03-19T17:21:40.158+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250319172140_ef1d8949-4f5b-47af-bc58-ece6c16ac550); Time taken: 0.02 seconds
[2025-03-19T17:21:40.159+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:21:40.160+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250319172140_ef1d8949-4f5b-47af-bc58-ece6c16ac550): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T17:21:40.161+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T17:21:40.162+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T17:21:40.162+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T17:21:40.163+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T17:21:40.163+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T17:21:40.164+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T17:21:40.165+0000] {subprocess.py:93} INFO -     )
[2025-03-19T17:21:40.166+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T17:21:40.167+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250319172140_ef1d8949-4f5b-47af-bc58-ece6c16ac550); Time taken: 0.002 seconds
[2025-03-19T17:21:40.168+0000] {subprocess.py:93} INFO - INFO  : OK
[2025-03-19T17:21:40.169+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T17:21:40.170+0000] {subprocess.py:93} INFO - No rows affected (0.115 seconds)
[2025-03-19T17:21:40.244+0000] {subprocess.py:93} INFO - Error: Error while compiling statement: FAILED: ParseException line 10:94 cannot recognize input near 'INTERVAL' ''1'' 'HOUR' in windowframeboundary (state=42000,code=40000)
[2025-03-19T17:21:40.257+0000] {subprocess.py:93} INFO - Closing: 0: jdbc:hive2://localhost:10000
[2025-03-19T17:21:40.330+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T17:21:40.348+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T17:21:40.355+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transactions_pipeline, task_id=detect_fraud, execution_date=20250319T171613, start_date=20250319T172135, end_date=20250319T172140
[2025-03-19T17:21:40.378+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task detect_fraud (Bash command failed. The command returned a non-zero exit code 1.; 436)
[2025-03-19T17:21:40.426+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T17:21:40.452+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
