[2025-03-21T13:50:03.321+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 scheduled__2025-03-21T13:42:39.231672+00:00 [queued]>
[2025-03-21T13:50:03.371+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 scheduled__2025-03-21T13:42:39.231672+00:00 [queued]>
[2025-03-21T13:50:03.372+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:50:03.411+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud_batch_20250321_131625> on 2025-03-21 13:42:39.231672+00:00
[2025-03-21T13:50:03.431+0000] {standard_task_runner.py:57} INFO - Started process 882 to run task
[2025-03-21T13:50:03.441+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud_batch_20250321_131625', 'scheduled__2025-03-21T13:42:39.231672+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpv1cr5df6']
[2025-03-21T13:50:03.447+0000] {standard_task_runner.py:85} INFO - Job 721: Subtask detect_fraud_batch_20250321_131625
[2025-03-21T13:50:03.551+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131625 scheduled__2025-03-21T13:42:39.231672+00:00 [running]> on host e95638583d4d
[2025-03-21T13:50:03.803+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud_batch_20250321_131625' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:42:39.231672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T13:42:39.231672+00:00'
[2025-03-21T13:50:03.808+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:50:03.810+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive spark-submit --master spark://localhost:7077 /hive/scripts/detect_fraud.py "batch_20250321_131625"\n            ']
[2025-03-21T13:50:03.865+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:50:36.788+0000] {subprocess.py:93} INFO - 25/03/21 13:50:36 INFO SparkContext: Running Spark version 3.5.0
[2025-03-21T13:50:36.802+0000] {subprocess.py:93} INFO - 25/03/21 13:50:36 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-21T13:50:36.804+0000] {subprocess.py:93} INFO - 25/03/21 13:50:36 INFO SparkContext: Java version 1.8.0_342
[2025-03-21T13:50:36.618+0000] {subprocess.py:93} INFO - 25/03/21 13:50:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-21T13:50:37.711+0000] {subprocess.py:93} INFO - 25/03/21 13:50:37 INFO ResourceUtils: ==============================================================
[2025-03-21T13:50:37.712+0000] {subprocess.py:93} INFO - 25/03/21 13:50:37 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-21T13:50:37.713+0000] {subprocess.py:93} INFO - 25/03/21 13:50:37 INFO ResourceUtils: ==============================================================
[2025-03-21T13:50:37.714+0000] {subprocess.py:93} INFO - 25/03/21 13:50:37 INFO SparkContext: Submitted application: FraudDetection
[2025-03-21T13:50:38.227+0000] {subprocess.py:93} INFO - 25/03/21 13:50:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-21T13:50:38.607+0000] {subprocess.py:93} INFO - 25/03/21 13:50:38 INFO ResourceProfile: Limiting resource is cpu
[2025-03-21T13:50:38.616+0000] {subprocess.py:93} INFO - 25/03/21 13:50:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-21T13:50:39.700+0000] {subprocess.py:93} INFO - 25/03/21 13:50:39 INFO SecurityManager: Changing view acls to: root
[2025-03-21T13:50:39.703+0000] {subprocess.py:93} INFO - 25/03/21 13:50:39 INFO SecurityManager: Changing modify acls to: root
[2025-03-21T13:50:39.706+0000] {subprocess.py:93} INFO - 25/03/21 13:50:39 INFO SecurityManager: Changing view acls groups to:
[2025-03-21T13:50:39.708+0000] {subprocess.py:93} INFO - 25/03/21 13:50:39 INFO SecurityManager: Changing modify acls groups to:
[2025-03-21T13:50:39.709+0000] {subprocess.py:93} INFO - 25/03/21 13:50:39 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root; groups with view permissions: EMPTY; users with modify permissions: root; groups with modify permissions: EMPTY
[2025-03-21T13:50:44.519+0000] {subprocess.py:93} INFO - 25/03/21 13:50:44 INFO Utils: Successfully started service 'sparkDriver' on port 40145.
[2025-03-21T13:50:45.301+0000] {subprocess.py:93} INFO - 25/03/21 13:50:45 INFO SparkEnv: Registering MapOutputTracker
[2025-03-21T13:50:46.011+0000] {subprocess.py:93} INFO - 25/03/21 13:50:46 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-21T13:50:46.303+0000] {subprocess.py:93} INFO - 25/03/21 13:50:46 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-21T13:50:46.308+0000] {subprocess.py:93} INFO - 25/03/21 13:50:46 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-21T13:50:46.312+0000] {subprocess.py:93} INFO - 25/03/21 13:50:46 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-21T13:50:47.900+0000] {subprocess.py:93} INFO - 25/03/21 13:50:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-247c05c4-0a69-48c9-970f-d9bf469c9cef
[2025-03-21T13:50:48.016+0000] {subprocess.py:93} INFO - 25/03/21 13:50:48 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
[2025-03-21T13:50:48.399+0000] {subprocess.py:93} INFO - 25/03/21 13:50:48 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-21T13:50:50.801+0000] {subprocess.py:93} INFO - 25/03/21 13:50:50 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-21T13:50:52.104+0000] {subprocess.py:93} INFO - 25/03/21 13:50:52 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-03-21T13:50:52.107+0000] {subprocess.py:93} INFO - 25/03/21 13:50:52 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-03-21T13:50:52.400+0000] {subprocess.py:93} INFO - 25/03/21 13:50:52 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2025-03-21T13:50:57.399+0000] {subprocess.py:93} INFO - 25/03/21 13:50:57 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2025-03-21T13:50:59.702+0000] {subprocess.py:93} INFO - 25/03/21 13:50:59 INFO TransportClientFactory: Successfully created connection to localhost/127.0.0.1:7077 after 1695 ms (0 ms spent in bootstraps)
[2025-03-21T13:51:03.609+0000] {subprocess.py:93} INFO - 25/03/21 13:51:03 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250321135103-0002
[2025-03-21T13:51:04.006+0000] {subprocess.py:93} INFO - 25/03/21 13:51:03 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36307.
[2025-03-21T13:51:04.008+0000] {subprocess.py:93} INFO - 25/03/21 13:51:03 INFO NettyBlockTransferService: Server created on e0b25feeb0e2:36307
[2025-03-21T13:51:04.103+0000] {subprocess.py:93} INFO - 25/03/21 13:51:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-21T13:51:04.816+0000] {subprocess.py:93} INFO - 25/03/21 13:51:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e0b25feeb0e2, 36307, None)
[2025-03-21T13:51:04.907+0000] {subprocess.py:93} INFO - 25/03/21 13:51:04 INFO BlockManagerMasterEndpoint: Registering block manager e0b25feeb0e2:36307 with 366.3 MiB RAM, BlockManagerId(driver, e0b25feeb0e2, 36307, None)
[2025-03-21T13:51:04.998+0000] {subprocess.py:93} INFO - 25/03/21 13:51:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e0b25feeb0e2, 36307, None)
[2025-03-21T13:51:04.999+0000] {subprocess.py:93} INFO - 25/03/21 13:51:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e0b25feeb0e2, 36307, None)
[2025-03-21T13:51:09.669+0000] {subprocess.py:93} INFO - 25/03/21 13:51:09 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-21T13:51:14.958+0000] {subprocess.py:93} INFO - Spark version: 3.5.0
[2025-03-21T13:51:16.550+0000] {subprocess.py:93} INFO - 25/03/21 13:51:16 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-21T13:51:27.349+0000] {subprocess.py:93} INFO - 25/03/21 13:51:27 INFO SharedState: Warehouse path is 'hdfs://localhost:9000/data/warehouse'.
[2025-03-21T13:51:53.016+0000] {subprocess.py:93} INFO - 25/03/21 13:51:53 INFO InMemoryFileIndex: It took 1698 ms to list leaf files for 1 paths.
[2025-03-21T13:52:04.442+0000] {subprocess.py:93} INFO - 25/03/21 13:52:04 INFO SparkContext: Starting job: parquet at NativeMethodAccessorImpl.java:0
[2025-03-21T13:52:04.959+0000] {subprocess.py:93} INFO - 25/03/21 13:52:04 INFO DAGScheduler: Got job 0 (parquet at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-21T13:52:04.960+0000] {subprocess.py:93} INFO - 25/03/21 13:52:04 INFO DAGScheduler: Final stage: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0)
[2025-03-21T13:52:05.059+0000] {subprocess.py:93} INFO - 25/03/21 13:52:05 INFO DAGScheduler: Parents of final stage: List()
[2025-03-21T13:52:05.061+0000] {subprocess.py:93} INFO - 25/03/21 13:52:05 INFO DAGScheduler: Missing parents: List()
[2025-03-21T13:52:05.444+0000] {subprocess.py:93} INFO - 25/03/21 13:52:05 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-21T13:52:06.546+0000] {subprocess.py:93} INFO - 25/03/21 13:52:06 INFO AsyncEventQueue: Process of event SparkListenerJobStart(0,1742565125049,WrappedArray(org.apache.spark.scheduler.StageInfo@1a23cf47),{spark.rdd.scope.noOverride=true, spark.rdd.scope={"id":"2","name":"collect"}}) by listener AppStatusListener took 1.315812775s.
[2025-03-21T13:52:07.044+0000] {subprocess.py:93} INFO - 25/03/21 13:52:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 103.3 KiB, free 366.2 MiB)
[2025-03-21T13:52:07.747+0000] {subprocess.py:93} INFO - 25/03/21 13:52:07 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 37.2 KiB, free 366.2 MiB)
[2025-03-21T13:52:07.763+0000] {subprocess.py:93} INFO - 25/03/21 13:52:07 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on e0b25feeb0e2:36307 (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:52:07.851+0000] {subprocess.py:93} INFO - 25/03/21 13:52:07 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1580
[2025-03-21T13:52:08.146+0000] {subprocess.py:93} INFO - 25/03/21 13:52:08 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at parquet at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-21T13:52:08.149+0000] {subprocess.py:93} INFO - 25/03/21 13:52:08 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-21T13:52:23.239+0000] {subprocess.py:93} INFO - 25/03/21 13:52:23 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-21T13:52:38.238+0000] {subprocess.py:93} INFO - 25/03/21 13:52:38 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-21T13:52:39.784+0000] {subprocess.py:93} INFO - 25/03/21 13:52:39 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250321135103-0002/0 on worker-20250321134653-172.18.0.2-40107 (172.18.0.2:40107) with 2 core(s)
[2025-03-21T13:52:39.786+0000] {subprocess.py:93} INFO - 25/03/21 13:52:39 INFO StandaloneSchedulerBackend: Granted executor ID app-20250321135103-0002/0 on hostPort 172.18.0.2:40107 with 2 core(s), 1024.0 MiB RAM
[2025-03-21T13:52:40.122+0000] {subprocess.py:93} INFO - 25/03/21 13:52:40 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250321135103-0002/0 is now RUNNING
[2025-03-21T13:52:45.578+0000] {subprocess.py:93} INFO - 25/03/21 13:52:45 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.2:39624) with ID 0,  ResourceProfileId 0
[2025-03-21T13:52:45.731+0000] {subprocess.py:93} INFO - 25/03/21 13:52:45 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.2:33447 with 366.3 MiB RAM, BlockManagerId(0, 172.18.0.2, 33447, None)
[2025-03-21T13:52:45.875+0000] {subprocess.py:93} INFO - 25/03/21 13:52:45 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.2, executor 0, partition 0, PROCESS_LOCAL, 7831 bytes)
[2025-03-21T13:52:46.918+0000] {subprocess.py:93} INFO - 25/03/21 13:52:46 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.2:33447 (size: 37.2 KiB, free: 366.3 MiB)
[2025-03-21T13:52:57.144+0000] {subprocess.py:93} INFO - 25/03/21 13:52:57 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.18.0.2 executor 0): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:52:57.145+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:52:57.146+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:52:57.147+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:52:57.147+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:52:57.148+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:52:57.148+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:52:57.149+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:52:57.149+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:52:57.149+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:52:57.150+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:52:57.151+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:52:57.151+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:52:57.152+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:52:57.155+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:52:57.155+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:52:57.156+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:52:57.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:52:57.157+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:52:57.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:52:57.158+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:52:57.158+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:52:57.159+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:52:57.159+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:52:57.160+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:57.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:57.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:57.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:57.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:57.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:57.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:57.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:57.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:57.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:57.163+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:57.163+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:57.164+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:57.164+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:57.164+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:57.165+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:57.165+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:57.165+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:52:57.166+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:52:57.166+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:52:57.166+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:52:57.166+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:52:57.167+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:52:57.167+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:52:57.168+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:52:57.168+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:52:57.169+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:52:57.169+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:52:57.169+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:52:57.169+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:52:57.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:52:57.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:52:57.171+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:52:57.171+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:52:57.171+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:52:57.171+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:52:57.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:52:57.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:52:57.172+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:52:57.173+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:52:57.173+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:52:57.173+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:52:57.173+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:52:57.174+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:52:57.174+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:52:57.174+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:52:57.175+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:52:57.175+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:52:57.175+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:52:57.176+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:52:57.176+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:52:57.176+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:57.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:57.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:57.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:57.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:57.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:57.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:57.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:57.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:57.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:57.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:57.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:57.181+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:57.181+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:57.181+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:57.182+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:57.182+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:57.182+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:52:57.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:52:57.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:52:57.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:52:57.184+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:52:57.184+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:52:57.184+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:52:57.185+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:52:57.186+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:52:57.186+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:52:57.188+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:52:57.188+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:52:57.188+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:52:57.189+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:52:57.189+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:52:57.189+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:52:57.190+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:52:57.190+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:52:57.190+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:52:57.190+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:57.230+0000] {subprocess.py:93} INFO - 25/03/21 13:52:57 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.18.0.2, executor 0, partition 0, PROCESS_LOCAL, 7831 bytes)
[2025-03-21T13:52:58.236+0000] {subprocess.py:93} INFO - 25/03/21 13:52:58 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.18.0.2, executor 0: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 1]
[2025-03-21T13:52:58.238+0000] {subprocess.py:93} INFO - 25/03/21 13:52:58 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.18.0.2, executor 0, partition 0, PROCESS_LOCAL, 7831 bytes)
[2025-03-21T13:52:58.724+0000] {subprocess.py:93} INFO - 25/03/21 13:52:58 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.18.0.2, executor 0: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 2]
[2025-03-21T13:52:58.729+0000] {subprocess.py:93} INFO - 25/03/21 13:52:58 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.18.0.2, executor 0, partition 0, PROCESS_LOCAL, 7831 bytes)
[2025-03-21T13:52:59.327+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.18.0.2, executor 0: org.apache.spark.SparkException (Exception thrown in awaitResult: ) [duplicate 3]
[2025-03-21T13:52:59.339+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2025-03-21T13:52:59.438+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-21T13:52:59.444+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO TaskSchedulerImpl: Cancelling stage 0
[2025-03-21T13:52:59.529+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.2 executor 0): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:52:59.533+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:52:59.540+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:52:59.541+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:52:59.543+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:52:59.544+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:52:59.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:52:59.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:52:59.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:52:59.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:52:59.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:52:59.548+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:52:59.548+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:52:59.550+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:52:59.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:52:59.551+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:52:59.552+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:52:59.555+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:52:59.556+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:52:59.557+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:52:59.557+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:52:59.559+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:52:59.559+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:52:59.560+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:52:59.561+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:59.561+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:59.562+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:59.562+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:59.563+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:59.563+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:59.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:59.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:59.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:59.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:59.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:59.566+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:59.566+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:59.566+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:59.567+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:59.567+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:59.568+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.568+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:52:59.568+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:52:59.569+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:52:59.570+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:52:59.570+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:52:59.571+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:52:59.572+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:52:59.574+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:52:59.575+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:52:59.576+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:52:59.577+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:52:59.578+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:52:59.579+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:52:59.580+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:52:59.580+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:52:59.581+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:52:59.581+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:52:59.582+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:52:59.583+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:52:59.583+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:52:59.584+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:52:59.585+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:52:59.586+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:52:59.586+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:52:59.587+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:52:59.587+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:52:59.587+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:52:59.588+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:52:59.589+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:52:59.589+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:52:59.590+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:52:59.590+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:52:59.591+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:52:59.593+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:52:59.594+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:59.595+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:59.595+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:59.596+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:59.596+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:59.597+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:59.597+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:59.597+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:59.598+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:59.599+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:59.599+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:59.599+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:59.600+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:59.600+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:59.601+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:59.602+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:59.602+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.603+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:52:59.603+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:52:59.603+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:52:59.604+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:52:59.604+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:52:59.605+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:52:59.605+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:52:59.606+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:52:59.606+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:52:59.606+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:52:59.607+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:52:59.607+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:52:59.608+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:52:59.608+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:52:59.609+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:52:59.609+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:52:59.610+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:52:59.610+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:52:59.610+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:52:59.611+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.611+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-03-21T13:52:59.612+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO DAGScheduler: ResultStage 0 (parquet at NativeMethodAccessorImpl.java:0) failed in 53.590 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.2 executor 0): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:52:59.613+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:52:59.613+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:52:59.614+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:52:59.614+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:52:59.614+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:52:59.615+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:52:59.624+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:52:59.626+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:52:59.627+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:52:59.630+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:52:59.631+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:52:59.635+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:52:59.645+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:52:59.646+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:52:59.647+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:52:59.647+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:52:59.649+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:52:59.649+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:52:59.650+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:52:59.651+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:52:59.652+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:52:59.652+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:52:59.653+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:52:59.654+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:59.654+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:59.655+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:59.656+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:59.656+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:59.657+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:59.658+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:59.658+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:59.659+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:59.660+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:59.661+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:59.661+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:59.662+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:59.662+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:59.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:59.664+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:59.664+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.665+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:52:59.666+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:52:59.667+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:52:59.668+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:52:59.668+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:52:59.669+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:52:59.669+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:52:59.670+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:52:59.671+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:52:59.671+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:52:59.671+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:52:59.672+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:52:59.672+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:52:59.673+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:52:59.673+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:52:59.674+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:52:59.675+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:52:59.675+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:52:59.676+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:52:59.676+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:52:59.676+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:52:59.677+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:52:59.678+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:52:59.678+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:52:59.679+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:52:59.679+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:52:59.680+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:52:59.680+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:52:59.682+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:52:59.683+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:52:59.684+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:52:59.684+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:52:59.684+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:52:59.685+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:52:59.685+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:52:59.685+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:52:59.686+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:52:59.686+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:52:59.686+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:52:59.687+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:52:59.687+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:52:59.687+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:52:59.688+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:52:59.688+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:52:59.688+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:52:59.689+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:52:59.689+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:52:59.689+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:52:59.690+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:52:59.690+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:52:59.690+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.691+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:52:59.692+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:52:59.692+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:52:59.692+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:52:59.693+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:52:59.693+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:52:59.693+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:52:59.694+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:52:59.694+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:52:59.695+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:52:59.695+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:52:59.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:52:59.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:52:59.697+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:52:59.698+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:52:59.698+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:52:59.699+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:52:59.700+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:52:59.701+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:52:59.702+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:52:59.702+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-03-21T13:52:59.703+0000] {subprocess.py:93} INFO - 25/03/21 13:52:59 INFO DAGScheduler: Job 0 failed: parquet at NativeMethodAccessorImpl.java:0, took 56.522198 s
[2025-03-21T13:53:01.041+0000] {subprocess.py:93} INFO - Error: An error occurred while calling o27.parquet.
[2025-03-21T13:53:01.043+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.2 executor 0): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:53:01.044+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:53:01.045+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:53:01.045+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:53:01.046+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:53:01.047+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:53:01.047+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:53:01.048+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$merge25/03/21 13:53:01 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-21T13:53:01.048+0000] {subprocess.py:93} INFO - SchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:53:01.049+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:53:01.050+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:53:01.058+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:53:01.061+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:53:01.062+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:53:01.063+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:53:01.064+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:53:01.065+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:53:01.066+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:53:01.067+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:53:01.068+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:53:01.068+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:53:01.069+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:53:01.070+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:53:01.070+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:53:01.071+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:53:01.071+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:01.072+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:01.072+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:01.072+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:01.073+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:01.073+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:01.073+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:01.074+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:01.074+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:01.075+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:01.075+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:01.075+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:01.076+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:01.076+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:01.077+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:01.077+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:01.078+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.078+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:53:01.079+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:53:01.079+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:53:01.080+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:53:01.081+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:53:01.082+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:53:01.082+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:53:01.083+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:53:01.083+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:53:01.084+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:53:01.085+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:53:01.086+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:53:01.086+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:53:01.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:53:01.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:53:01.088+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:53:01.088+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:53:01.089+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:53:01.089+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:53:01.090+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:53:01.090+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:53:01.091+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:53:01.091+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:53:01.091+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:53:01.091+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:53:01.092+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:53:01.092+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:53:01.093+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:53:01.093+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:53:01.093+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:53:01.094+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:53:01.094+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:53:01.094+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:53:01.095+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:53:01.095+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:01.095+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:01.096+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:01.096+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:01.096+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:01.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:01.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:01.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:01.098+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:01.098+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:01.098+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:01.099+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:01.100+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:01.100+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:01.101+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:01.102+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:01.102+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:53:01.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:53:01.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:53:01.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:53:01.104+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:53:01.104+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:53:01.105+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:53:01.105+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:01.105+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:01.105+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:01.106+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:01.106+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:53:01.106+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:53:01.107+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:53:01.107+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:53:01.107+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:53:01.107+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:53:01.108+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:53:01.108+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:53:01.108+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.109+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-03-21T13:53:01.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2844)
[2025-03-21T13:53:01.109+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2780)
[2025-03-21T13:53:01.110+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2779)
[2025-03-21T13:53:01.110+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-21T13:53:01.110+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-21T13:53:01.111+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-21T13:53:01.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2779)
[2025-03-21T13:53:01.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1242)
[2025-03-21T13:53:01.111+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1242)
[2025-03-21T13:53:01.112+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-21T13:53:01.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1242)
[2025-03-21T13:53:01.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3048)
[2025-03-21T13:53:01.112+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2982)
[2025-03-21T13:53:01.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2971)
[2025-03-21T13:53:01.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-21T13:53:01.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:984)
[2025-03-21T13:53:01.113+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
[2025-03-21T13:53:01.114+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
[2025-03-21T13:53:01.114+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
[2025-03-21T13:53:01.114+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
[2025-03-21T13:53:01.114+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1046)
[2025-03-21T13:53:01.115+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-21T13:53:01.115+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-21T13:53:01.116+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:407)
[2025-03-21T13:53:01.116+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.collect(RDD.scala:1045)
[2025-03-21T13:53:01.117+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:73)
[2025-03-21T13:53:01.117+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:497)
[2025-03-21T13:53:01.118+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:132)
[2025-03-21T13:53:01.118+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:79)
[2025-03-21T13:53:01.119+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-03-21T13:53:01.119+0000] {subprocess.py:93} INFO - 	at scala.Option.orElse(Option.scala:447)
[2025-03-21T13:53:01.119+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-03-21T13:53:01.120+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-03-21T13:53:01.120+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-21T13:53:01.121+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-21T13:53:01.121+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-03-21T13:53:01.121+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-21T13:53:01.122+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-03-21T13:53:01.122+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:01.122+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:01.122+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:01.123+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:01.123+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-21T13:53:01.123+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-21T13:53:01.123+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-21T13:53:01.124+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-21T13:53:01.124+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-21T13:53:01.124+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-21T13:53:01.124+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-21T13:53:01.125+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:53:01.125+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:53:01.125+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:53:01.125+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:53:01.125+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:53:01.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:53:01.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:53:01.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:53:01.126+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:53:01.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:53:01.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:53:01.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:53:01.127+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:53:01.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:53:01.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:53:01.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:53:01.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:53:01.128+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:53:01.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:53:01.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:53:01.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:53:01.129+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:53:01.130+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:53:01.130+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:53:01.135+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-03-21T13:53:01.139+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:01.141+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:01.142+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:01.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:01.144+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:01.144+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:01.145+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:01.146+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:01.146+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:01.147+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:01.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:01.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:01.149+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:01.149+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:01.150+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:01.151+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:01.152+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.153+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:53:01.153+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:53:01.154+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:53:01.155+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:53:01.155+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:53:01.156+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:53:01.157+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:53:01.159+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:53:01.159+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:53:01.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:53:01.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:53:01.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:53:01.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:53:01.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:53:01.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:53:01.163+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:53:01.163+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:53:01.164+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:53:01.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:53:01.164+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:53:01.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:53:01.165+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:53:01.166+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:53:01.166+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:53:01.166+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:53:01.166+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:53:01.167+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:53:01.167+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:53:01.167+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:53:01.168+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:53:01.168+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:53:01.169+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:53:01.169+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:53:01.169+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:53:01.170+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:01.171+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:01.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:01.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:01.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:01.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:01.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:01.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:01.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:01.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:01.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:01.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:01.175+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:01.175+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:01.175+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:01.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:01.176+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:53:01.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:53:01.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:53:01.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:53:01.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:53:01.177+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:53:01.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:53:01.177+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:53:01.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:53:01.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:53:01.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:53:01.179+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:53:01.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:53:01.180+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:53:01.180+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:01.180+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO SparkUI: Stopped Spark web UI at http://e0b25feeb0e2:4042
[2025-03-21T13:53:01.254+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-21T13:53:01.259+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-21T13:53:01.641+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-21T13:53:01.843+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO MemoryStore: MemoryStore cleared
[2025-03-21T13:53:01.844+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO BlockManager: BlockManager stopped
[2025-03-21T13:53:01.944+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-21T13:53:01.959+0000] {subprocess.py:93} INFO - 25/03/21 13:53:01 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-21T13:53:02.151+0000] {subprocess.py:93} INFO - 25/03/21 13:53:02 INFO SparkContext: Successfully stopped SparkContext
[2025-03-21T13:53:02.242+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-21T13:53:02.244+0000] {subprocess.py:93} INFO -   File "/hive/scripts/detect_fraud.py", line 15, in <module>
[2025-03-21T13:53:02.250+0000] {subprocess.py:93} INFO -     df_transactions = spark.read.parquet(f"/data/transactions/transactions_{batch_id}/*.parquet")
[2025-03-21T13:53:02.252+0000] {subprocess.py:93} INFO -   File "/opt/spark-3.5.0-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-03-21T13:53:02.261+0000] {subprocess.py:93} INFO -   File "/opt/spark-3.5.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-21T13:53:02.262+0000] {subprocess.py:93} INFO -   File "/opt/spark-3.5.0-bin-hadoop3/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-03-21T13:53:02.264+0000] {subprocess.py:93} INFO -   File "/opt/spark-3.5.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-03-21T13:53:02.343+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o27.parquet.
[2025-03-21T13:53:02.349+0000] {subprocess.py:93} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.18.0.2 executor 0): org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:53:02.350+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:53:02.351+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:53:02.362+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:53:02.363+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:53:02.364+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:53:02.365+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:53:02.366+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:53:02.367+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:53:02.367+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:53:02.368+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:53:02.368+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:53:02.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:53:02.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:53:02.369+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:53:02.371+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:53:02.372+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:53:02.372+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:53:02.373+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:53:02.373+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:53:02.374+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:53:02.374+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:53:02.375+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:53:02.375+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:53:02.376+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:02.376+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:02.377+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:02.377+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:02.378+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:02.378+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:02.379+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:02.379+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:02.380+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:02.380+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:02.381+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:02.381+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:02.382+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:02.382+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:02.383+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:02.383+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:02.384+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.384+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:53:02.385+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:53:02.393+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:53:02.394+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:53:02.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:53:02.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:53:02.395+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:53:02.396+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:53:02.396+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:53:02.396+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:53:02.397+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:53:02.397+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:53:02.397+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:53:02.398+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:53:02.398+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:53:02.399+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:53:02.399+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:53:02.399+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:53:02.400+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:53:02.400+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:53:02.401+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:53:02.401+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:53:02.402+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:53:02.402+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:53:02.403+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:53:02.403+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:53:02.403+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:53:02.404+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:53:02.405+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:53:02.405+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:53:02.406+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:53:02.407+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:53:02.407+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:53:02.408+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:53:02.408+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:02.409+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:02.409+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:02.410+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:02.410+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:02.410+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:02.411+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:02.411+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:02.412+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:02.412+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:02.412+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:02.413+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:02.413+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:02.414+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:02.414+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:02.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:02.415+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:53:02.416+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:53:02.416+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:53:02.417+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:53:02.417+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:53:02.418+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:53:02.418+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:53:02.418+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:02.419+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:02.420+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:02.420+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:02.421+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:53:02.421+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:53:02.422+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:53:02.422+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:53:02.423+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:53:02.423+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:53:02.424+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:53:02.424+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:53:02.424+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.425+0000] {subprocess.py:93} INFO - Driver stacktrace:
[2025-03-21T13:53:02.426+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2844)
[2025-03-21T13:53:02.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2780)
[2025-03-21T13:53:02.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2779)
[2025-03-21T13:53:02.428+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-21T13:53:02.428+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-21T13:53:02.429+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-21T13:53:02.429+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2779)
[2025-03-21T13:53:02.430+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1242)
[2025-03-21T13:53:02.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1242)
[2025-03-21T13:53:02.437+0000] {subprocess.py:93} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-21T13:53:02.438+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1242)
[2025-03-21T13:53:02.439+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3048)
[2025-03-21T13:53:02.440+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2982)
[2025-03-21T13:53:02.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2971)
[2025-03-21T13:53:02.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-21T13:53:02.442+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:984)
[2025-03-21T13:53:02.443+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
[2025-03-21T13:53:02.443+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
[2025-03-21T13:53:02.444+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
[2025-03-21T13:53:02.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
[2025-03-21T13:53:02.445+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1046)
[2025-03-21T13:53:02.446+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-21T13:53:02.447+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-21T13:53:02.447+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:407)
[2025-03-21T13:53:02.448+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.collect(RDD.scala:1045)
[2025-03-21T13:53:02.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.mergeSchemasInParallel(SchemaMergeUtils.scala:73)
[2025-03-21T13:53:02.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:497)
[2025-03-21T13:53:02.450+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetUtils$.inferSchema(ParquetUtils.scala:132)
[2025-03-21T13:53:02.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:79)
[2025-03-21T13:53:02.451+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-03-21T13:53:02.452+0000] {subprocess.py:93} INFO - 	at scala.Option.orElse(Option.scala:447)
[2025-03-21T13:53:02.454+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-03-21T13:53:02.455+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-03-21T13:53:02.456+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-21T13:53:02.457+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-21T13:53:02.457+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-03-21T13:53:02.458+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-21T13:53:02.459+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-03-21T13:53:02.460+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:02.462+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:02.462+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:02.463+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:02.463+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-21T13:53:02.464+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-21T13:53:02.464+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-21T13:53:02.464+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-21T13:53:02.465+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-21T13:53:02.465+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-21T13:53:02.466+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-21T13:53:02.466+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-21T13:53:02.466+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-21T13:53:02.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-21T13:53:02.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-21T13:53:02.468+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[2025-03-21T13:53:02.468+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:443)
[2025-03-21T13:53:02.468+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:493)
[2025-03-21T13:53:02.469+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:485)
[2025-03-21T13:53:02.469+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:79)
[2025-03-21T13:53:02.470+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2025-03-21T13:53:02.470+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2025-03-21T13:53:02.470+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-21T13:53:02.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
[2025-03-21T13:53:02.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
[2025-03-21T13:53:02.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-21T13:53:02.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
[2025-03-21T13:53:02.472+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-21T13:53:02.472+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-21T13:53:02.473+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-21T13:53:02.473+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-21T13:53:02.473+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-21T13:53:02.474+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-21T13:53:02.474+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-21T13:53:02.475+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-21T13:53:02.475+0000] {subprocess.py:93} INFO - 	... 1 more
[2025-03-21T13:53:02.475+0000] {subprocess.py:93} INFO - Caused by: java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:02.476+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:02.476+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:02.477+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:02.477+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:02.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:02.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:02.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:02.479+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:02.479+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:02.480+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:02.480+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:02.481+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:02.481+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:02.481+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:02.482+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:02.482+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.483+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-21T13:53:02.483+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-21T13:53:02.484+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-21T13:53:02.484+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-21T13:53:02.484+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-21T13:53:02.485+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-21T13:53:02.485+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:902)
[2025-03-21T13:53:02.485+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:889)
[2025-03-21T13:53:02.486+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:878)
[2025-03-21T13:53:02.486+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1046)
[2025-03-21T13:53:02.486+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:340)
[2025-03-21T13:53:02.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:336)
[2025-03-21T13:53:02.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-03-21T13:53:02.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:353)
[2025-03-21T13:53:02.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-03-21T13:53:02.488+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69)
[2025-03-21T13:53:02.488+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:796)
[2025-03-21T13:53:02.488+0000] {subprocess.py:93} INFO - 	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:666)
[2025-03-21T13:53:02.488+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:85)
[2025-03-21T13:53:02.489+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFooterReader.readFooter(ParquetFooterReader.java:76)
[2025-03-21T13:53:02.489+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:450)
[2025-03-21T13:53:02.489+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:380)
[2025-03-21T13:53:02.489+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-03-21T13:53:02.490+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-03-21T13:53:02.490+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-03-21T13:53:02.490+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-03-21T13:53:02.490+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-03-21T13:53:02.491+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-03-21T13:53:02.491+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-03-21T13:53:02.491+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[2025-03-21T13:53:02.491+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[2025-03-21T13:53:02.491+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[2025-03-21T13:53:02.492+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[2025-03-21T13:53:02.492+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2025-03-21T13:53:02.492+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_20250321_131625/transactions_batch_20250321_131625.parquet
[2025-03-21T13:53:02.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
[2025-03-21T13:53:02.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
[2025-03-21T13:53:02.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:153)
[2025-03-21T13:53:02.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1927)
[2025-03-21T13:53:02.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
[2025-03-21T13:53:02.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:424)
[2025-03-21T13:53:02.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-21T13:53:02.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-21T13:53:02.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-21T13:53:02.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-21T13:53:02.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-21T13:53:02.497+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-21T13:53:02.497+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-21T13:53:02.497+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-21T13:53:02.497+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-21T13:53:02.498+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1612)
[2025-03-21T13:53:02.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-03-21T13:53:02.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-03-21T13:53:02.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-03-21T13:53:02.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-03-21T13:53:02.499+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy31.getBlockLocations(Unknown Source)
[2025-03-21T13:53:02.499+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
[2025-03-21T13:53:02.500+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-21T13:53:02.500+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-21T13:53:02.500+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-21T13:53:02.500+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-21T13:53:02.500+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-21T13:53:02.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-21T13:53:02.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-21T13:53:02.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-21T13:53:02.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-21T13:53:02.502+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy32.getBlockLocations(Unknown Source)
[2025-03-21T13:53:02.502+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:900)
[2025-03-21T13:53:02.502+0000] {subprocess.py:93} INFO - 	... 27 more
[2025-03-21T13:53:02.502+0000] {subprocess.py:93} INFO - 
[2025-03-21T13:53:02.747+0000] {subprocess.py:93} INFO - 25/03/21 13:53:02 INFO ShutdownHookManager: Shutdown hook called
[2025-03-21T13:53:02.750+0000] {subprocess.py:93} INFO - 25/03/21 13:53:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-81de4dd0-1f9b-4f9c-8f65-f76f7b936bcc/pyspark-aeae0ba5-99ef-4337-b67a-30976328e285
[2025-03-21T13:53:02.761+0000] {subprocess.py:93} INFO - 25/03/21 13:53:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-9ad958f2-e51f-4906-961d-e95efc8a32f2
[2025-03-21T13:53:02.839+0000] {subprocess.py:93} INFO - 25/03/21 13:53:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-81de4dd0-1f9b-4f9c-8f65-f76f7b936bcc
[2025-03-21T13:53:03.272+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-21T13:53:03.291+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-21T13:53:03.300+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=detect_fraud_batch_20250321_131625, execution_date=20250321T134239, start_date=20250321T135003, end_date=20250321T135303
[2025-03-21T13:53:03.356+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-21T13:53:03.358+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:53:03.359+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:53:03.379+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:53:03.379+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:53:03.380+0000] {taskinstance.py:2005} ERROR - Failed to send email to: rabiizahnoune7@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-21T13:53:03.405+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-21T13:53:03.405+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-03-21T13:53:03.406+0000] {taskinstance.py:1703} ERROR - Error when executing on_failure_callback callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1700, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/fraud_detection_pipeline.py", line 27, in on_failure_callback
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-21T13:53:03.427+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 721 for task detect_fraud_batch_20250321_131625 (Bash command failed. The command returned a non-zero exit code 1.; 882)
[2025-03-21T13:53:03.490+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T13:53:03.529+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
